### ISSUE TITLE
Slurm sacct output not parsed correctly?

### ISSUE THREAD

**Issue by jpecar** [gc3pie/gc3pie#656]
I'm using easybuild 4.0 to submit jobs to our cluster via gc3pie 2.6.4. It is mostly working (software gets built) but gc3pie is somehow not aware of that.

Debug log shows:
```
== 2019-11-13 09:34:07,778 transport.py:1083 DEBUG Executed local command 'env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 46601126', got exit status: 0
== 2019-11-13 09:34:07,778 batch.py:623 DEBUG Gathered accounting info {u'duration': Duration(0, unit=s), u'cores': 0, u'max_used_memory': Memory(0, unit=B), u'used_cpu_time': Duration(0, unit=s)} for task Application@7f9dad785ed0
== 2019-11-13 09:34:07,779 __init__.py:625 DEBUG Calling state-transition handler 'unknown' on Application@7f9dad785ed0 ...
== 2019-11-13 09:34:07,779 core.py:463 DEBUG Error getting status of application 'Application@7f9dad785ed0': LRMSError: Could not retrieve status information for task Application@7f9dad785ed0
```

Actual output of that sacct command is:
```
$ env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 46601126
46601126|0:0|COMPLETED|4|00:00:52|00:36.857|2019-11-13T10:32:32|2019-11-13T10:32:35|2019-11-13T10:33:27|||
46601126.batch|0:0|COMPLETED|4|00:00:52|00:00.031|2019-11-13T10:32:35|2019-11-13T10:32:35|2019-11-13T10:33:27|7360K|427400K|
46601126.extern|0:0|COMPLETED|4|00:00:52|00:00:00|2019-11-13T10:32:35|2019-11-13T10:32:35|2019-11-13T10:33:27|1252K|184348K|
46601126.0|0:0|COMPLETED|4|00:00:51|00:36.824|2019-11-13T10:32:36|2019-11-13T10:32:36|2019-11-13T10:33:27|56472K|841688K|
```
We're running slurm 18.08.7 and plan to move on to 19.x soon.

**Comment by riccardomurri** [comment]
I presume no STDERR output from the `sacct` command?

**Comment by jpecar** [comment]
Correct, no complains on stderr and exit status is 0.

**Comment by riccardomurri** [comment]
I cannot reproduce this... I plugged the `sacct` output lines you provided into a test case, and they are parsed correctly.  Is it possible that EB/GC3Pie is using a different `sacct` command than your login shell?

**Comment by riccardomurri** [comment]
Is it possible that `sacct` exits with code 0 and no output when the job has too recently finished?

**Comment by riccardomurri** [comment]
Could you pls apply this patch to `gc3libs/backends/slurm.py` and re-run (with DEBUG logging)?

```diff
diff --git a/gc3libs/backends/batch.py b/gc3libs/backends/batch.py
index eb7dbe99..8a44cfca 100755
--- a/gc3libs/backends/batch.py
+++ b/gc3libs/backends/batch.py
@@ -550,6 +550,7 @@ class BatchSystem(LRMS):
     def __run_command_and_parse_output(self, cmd, parser, kind='accounting'):
         log.debug("Checking remote job %s info with `%s` ...", kind, cmd)
         exit_code, stdout, stderr = self.transport.execute_command(cmd)
+        log.debug("Command `%s`: exitcode=%r, STDOUT=%r, STDERR=%r", exit_code, stdout, stderr)
         if exit_code == 0:
             return parser(stdout, stderr)
         else:
```

**Comment by jpecar** [comment]
I've rebuilt our buildenv docker to make sure it has the same versions of binaries as the cluster. No change, still the same behaviour.

I've applied your patch, noticed that first %s does not have a match, removed whole Command part since cmd is printed two lines above anyway. It acts strange - all outputs of this log line have empty stdout and stderr, even the one for squeue, but counting jobs actually works correctly. 
```
== 2019-11-13 13:42:23,108 transport.py:1083 DEBUG Executed local command 'env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 46628133', got exit status: 0
== 2019-11-13 13:42:23,108 batch.py:553 DEBUG exitcode=0, STDOUT='', STDERR=u''
== 2019-11-13 13:42:23,108 batch.py:624 DEBUG Gathered accounting info {u'duration': Duration(0, unit=s), u'cores': 0, u'max_used_memory': Memory(0, unit=B), u'used_cpu_time': Duration(0, unit=s)} for task Application@7f328683fcd0
== 2019-11-13 13:42:23,109 __init__.py:625 DEBUG Calling state-transition handler 'unknown' on Application@7f328683fcd0 ...
== 2019-11-13 13:42:23,109 core.py:463 DEBUG Error getting status of application 'Application@7f328683fcd0': LRMSError: Could not retrieve status information for task Application@7f328683fcd0
```

**Comment by riccardomurri** [comment]
Is EB/GC3Pie running on Py2 or Py3 in your buildenv?

**Comment by jpecar** [comment]
Py2, stock el7 environment.

**Comment by riccardomurri** [comment]
Ok, so the problem seems to be that somehow STDOUT of `sacct` is not read.

1. I can (probably should) alter the batch-queueing backend to error out on empty `sacct` output, instead of happily setting the job's duration to 0s, exit code to 0, etc. as it does now.

2. As to why `sacct` output is not reaped... that's puzzling.  The output from `sbatch` is correctly read, otherwise the job ID would be unknown / submission would be considered failed by GC3Pie; similarly for `squeue`.  Is there some localized output in `sacct` that could make charset conversion fail?  Does the same happen if you re-run the same with LANG unset and LC_ALL set to "C" ?

**Comment by jpecar** [comment]
I unset LANG and set LC_ALL=C in our build script, rerun the pipeline, verified in EB debug output that these values were taken in, but still got the same behavior.

Anything else I can try?

**Comment by jpecar** [comment]
I tested the obvious (run sacct manually from within our docker container) and immediately spotted the issue, a missing /etc/hosts entry. So nothing related to gc3pie, sorry for the noise.

**Comment by riccardomurri** [comment]
All is well that ends well :-)
