### ISSUE TITLE
LocalTransport execute_command() returns stdout as stderr

### ISSUE THREAD

**Issue by ryantaylor-cu** [gc3pie/gc3pie#661]
To learn gc3pie, I setup a resource with transport=local.  I get this error, even though mktemp correctly creates the directory:

Got error in submitting task 'GdemoSimpleApp@7f3fceea1eb8', informing scheduler: LRMSSubmitError: Failed submitting task GdemoSimpleApp@7f3fceea1eb8 to resource `localhost`: Cannot create temporary job working directory `$HOME/.gc3pie_jobs/shellcmd_job.XXXXXX` on host `localhost`; command `mkdir -p $HOME/.gc3pie_jobs && mktemp -d $HOME/.gc3pie_jobs/shellcmd_job.XXXXXX` exited with code 0 and error output: `/home/ryantaylor/.gc3pie_jobs/shellcmd_job.GFLO22

**Comment by riccardomurri** [comment]
Fixed by #662
