### ISSUE TITLE
Need to make explicit that license is GC3Pie is LGPLv2+

### ISSUE THREAD

**Issue by riccardomurri** [gc3pie/gc3pie#666]
Although GC3Pie has been LGPL-licensed since its inception (all `.py` files bear the relevant notice), there is no top-level `LICENSE.txt` file nor any mention of the license in the `README.rst` file or in the docs.

Please add it!

**Comment by riccardomurri** [comment]
How apt that this issue got #666 ... "the devil is in the details".

**Comment by smaffiol** [comment]
I can take this up
license.txt will contain the text extracted from: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
is this correct ?

**Comment by riccardomurri** [comment]
Yes, correct.  Note they also have a markdown text version which might be better for inclusion in the repo: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.md -- you can just copy the file verbatim into the top-level repository directory.

**Comment by riccardomurri** [comment]
Fixed by @smaffiol in commit 64243b13f5bf4b81742a4f55a03375b3dc7c40f2
