### ISSUE TITLE
workaround for paramiko key problem

### ISSUE THREAD

**Issue by martinschorb** [gc3pie/gc3pie#669]
Hi,

would a similar workaround as for elasticluster be possible to make gc3pie work when paramiko comes up with the key type problem?

https://github.com/elasticluster/elasticluster/commit/50223b3bd6218da9cf2ccf369f369d211524a454

**Comment by riccardomurri** [comment]
Thank you for the suggestion!  This should be fixed in GC3Pie v2.6.7, released today, and in the "master" branch.

Please re-open if you see that you run into this same error again.
